# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160228_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=2100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text='Description meta tag', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Product page URL.', max_length=255, unique=True),
        ),
    ]
