# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
