# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
